[package]
name = "Backend"
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"

[lints]
workspace = true

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
async-trait = "0.1.83"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_with = "3.9.0"

axum = "0.7.6"
tower-http = { version = "0.6.1", features = ["fs"] }
tower-cookies = "0.10.0"

lazy-regex = "3.3.0"
strum_macros = "0.26.4"
uuid = { version = "1", features = ["v4", "fast-rng"] }


[dev-dependencies]
anyhow = "1.0.89"
httpc-test = "0.1.10"