-- Insert states
INSERT INTO "states" (name) VALUES
('Johor'),
('Kedah'),
('Kelantan'),
('Melaka'),
('Negeri Sembilan'),
('Pahang'),
('Perak'),
('Perlis'),
('Pulau Pinang'),
('Sabah'),
('Sarawak'),
('Selangor'),
('Terengganu'),
('W.P. Kuala Lumpur'),
('W.P. Labuan'),
('W.P. Putrajaya');

-- Insert districts
INSERT INTO "districts" (name, state_id) VALUES
-- Johor
('Batu Pahat', 1),
('Johor Bahru', 1),
('Kluang', 1),
('Kota Tinggi', 1),
('Kulai', 1),
('Mersing', 1),
('Muar', 1),
('Pontian', 1),
('Segamat', 1),
('Tangkak', 1),

-- Kedah
('Baling', 2),
('Bandar Baharu', 2),
('Kota Setar', 2),
('Kuala Muda', 2),
('Kubang Pasu', 2),
('Kulim', 2),
('Langkawi', 2),
('Padang Terap', 2),
('Pendang', 2),
('Pokok Sena', 2),
('Sik', 2),
('Yan', 2),

-- Kelantan
('Bachok', 3),
('Gua Musang', 3),
('Jeli', 3),
('Kecil Lojing', 3),
('Kota Bharu', 3),
('Kuala Krai', 3),
('Machang', 3),
('Pasir Mas', 3),
('Pasir Puteh', 3),
('Tanah Merah', 3),
('Tumpat', 3),

-- Melaka
('Alor Gajah', 4),
('Jasin', 4),
('Melaka Tengah', 4),

-- Negeri Sembilan
('Jelebu', 5),
('Jempol', 5),
('Kuala Pilah', 5),
('Port Dickson', 5),
('Rembau', 5),
('Seremban', 5),
('Tampin', 5),

-- Pahang
('Bentong', 6),
('Bera', 6),
('Cameron Highlands', 6),
('Jerantut', 6),
('Kuantan', 6),
('Lipis', 6),
('Maran', 6),
('Pekan', 6),
('Raub', 6),
('Rompin', 6),
('Temerloh', 6),

-- Perak
('Bagan Datuk', 7),
('Batang Padang', 7),
('Hilir Perak', 7),
('Hulu Perak', 7),
('Kampar', 7),
('Kerian', 7),
('Kinta', 7),
('Kuala Kangsar', 7),
('Larut Dan Matang', 7),
('Manjung', 7),
('Muallim', 7),
('Perak Tengah', 7),
('Selama', 7),

-- Perlis
('Perlis', 8),

-- Pulau Pinang
('Barat Daya', 9),
('Seberang Perai Selatan', 9),
('Seberang Perai Tengah', 9),
('Seberang Perai Utara', 9),
('Timur Laut', 9),

-- Sabah
('Beaufort', 10),
('Beluran', 10),
('Kalabakan', 10),
('Keningau', 10),
('Kinabatangan', 10),
('Kota Belud', 10),
('Kota Kinabalu', 10),
('Kota Marudu', 10),
('Kuala Penyu', 10),
('Kudat', 10),
('Kunak', 10),
('Lahad Datu', 10),
('Nabawan', 10),
('Papar', 10),
('Penampang', 10),
('Pitas', 10),
('Putatan', 10),
('Ranau', 10),
('Sandakan', 10),
('Semporna', 10),
('Sipitang', 10),
('Tambunan', 10),
('Tawau', 10),
('Telupid', 10),
('Tenom', 10),
('Tongod', 10),
('Tuaran', 10),

-- Sarawak
('Asajaya', 11),
('Bau', 11),
('Belaga', 11),
('Beluru', 11),
('Betong', 11),
('Bintulu', 11),
('Bukit Mabong', 11),
('Dalat', 11),
('Daro', 11),
('Julau', 11),
('Kabong', 11),
('Kanowit', 11),
('Kapit', 11),
('Kuching', 11),
('Lawas', 11),
('Limbang', 11),
('Lubok Antu', 11),
('Lundu', 11),
('Maradong', 11),
('Marudi', 11),
('Matu', 11),
('Miri', 11),
('Mukah', 11),
('Pakan', 11),
('Pusa', 11),
('Samarahan', 11),
('Saratok', 11),
('Sarikei', 11),
('Sebauh', 11),
('Selangau', 11),
('Serian', 11),
('Sibu', 11),
('Simunjan', 11),
('Song', 11),
('Sri Aman', 11),
('Subis', 11),
('Tanjung Manis', 11),
('Tatau', 11),
('Tebedu', 11),
('Telang Usan', 11),

-- Selangor
('Gombak', 12),
('Klang', 12),
('Kuala Langat', 12),
('Kuala Selangor', 12),
('Petaling', 12),
('Sabak Bernam', 12),
('Sepang', 12),
('Ulu Langat', 12),
('Ulu Selangor', 12),

-- Terengganu
('Besut', 13),
('Dungun', 13),
('Hulu Terengganu', 13),
('Kemaman', 13),
('Kuala Nerus', 13),
('Kuala Terengganu', 13),
('Marang', 13),
('Setiu', 13),

-- W.P. Kuala Lumpur
('W.P. Kuala Lumpur', 14),

-- W.P. Labuan
('W.P. Labuan', 15),

-- W.P. Putrajaya
('W.P. Putrajaya', 16);
